%% in the couchdb interface
%% Open "gothenburg" Database
%% click on create a new document
%% Paste this codes and save
%% then run the queries

{
   "_id": "_design/by_price_rooms",
   "language": "erlang",
   "views": {
       "rent_0-3000_rooms_1-2": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 0, M =< 3000 ->\ncase V2 of \n<<\"1\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"1.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"2\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_3-4": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 0, M =< 3000 ->\ncase V2 of \n<<\"3\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"3.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"4\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_plus_5": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 0, M =< 3000 ->\ncase V2 of \n<<\"5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"6\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"7\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_1-2": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 3001, M =< 6000 ->\ncase V2 of \n<<\"1\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"1.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"2\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_3-4": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 3001, M =< 6000 ->\ncase V2 of \n<<\"3\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"3.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"4\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_plus_5": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 3001, M =< 6000 ->\ncase V2 of \n<<\"5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"6\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"7\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_1-2": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 6001, M =< 12000 ->\ncase V2 of \n<<\"1\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"1.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"2\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_3-4": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 6001, M =< 12000 ->\ncase V2 of \n<<\"3\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"3.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"4\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_plus_5": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 6001, M =< 12000 ->\ncase V2 of \n<<\"5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"6\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"7\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_1-2": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 12001 ->\ncase V2 of \n<<\"1\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"1.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"2\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_3-4": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 12001 ->\ncase V2 of \n<<\"3\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"3.5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"4\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_plus_5": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 12001 ->\ncase V2 of \n<<\"5\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"6\">>->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n<<\"7\">>-> Ko =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend;\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_any": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 12001 ->\n\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_any": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 6001, M =< 12000 ->\n\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_any": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 3001, M =< 6000 ->\n\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_any": {
           "map": "\nfun({Doc}) ->\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),     \nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 0, M =< 3000 ->\n\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n\n_-> ok\nend\n end.\n          \n       ",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       }
   }
}
