{
   "_id": "_design/by_price_rooms",
   "_rev": "1-d75cffa400c786a68078aeb8371e7f7b",
   "language": "erlang",
   "views": {
       "rent_0-3000_rooms_1-2": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 0, M =< 3000 ->\n\t\t\tcase V2 of X2 when X >= 1, X =< 2 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_3-4": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 0, M =< 3000 ->\n\t\t\tcase V2 of X2 when X >= 3, X =< 4 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_plus_5": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 0, M =< 3000 ->\n\t\t\tcase V2 of X2 when X >= 5 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_1-2": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 3001, M =< 6000 ->\n\t\t\tcase V2 of X2 when X >= 1, X =< 2 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_3-4": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 3001, M =< 6000 ->\n\t\t\tcase V2 of X2 when X >= 3, X =< 4 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_plus_5": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 3001, M =< 6000 ->\n\t\t\tcase V2 of X2 when X >= 5 ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_1-2": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 6001, M =< 12000 ->\n\t\t\tcase V2 of X2 when X >= 1, X =< 2  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_3-4": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 6001, M =< 12000 ->\n\t\t\tcase V2 of X2 when X >= 3, X =< 4  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_plus_5": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 6001, M =< 12000 ->\n\t\t\tcase V2 of X2 when X >= 5  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_1-2": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 12001 ->\n\t\t\tcase V2 of X2 when X >= 1, X =< 2  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_3-4": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 12001 ->\n\t\t\tcase V2 of X2 when X >= 3, X =< 4  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_plus_5": {
           "map": "fun({Doc}) ->\n\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),      \n\tX=list_to_integer(binary_to_list(V2)),\n\tX2 = list_to_binary(integer_to_list(X)),\n\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),      \n\tM=list_to_integer(binary_to_list(V1)),\n\tM2 = list_to_binary(integer_to_list(M)),\n\t\t\n\t\tcase V1 of M2 when M >= 12001 ->\n\t\t\tcase V2 of X2 when X >= 5  ->\n\t\t\t\tKo =proplists:get_value(<<\"_rev\">>, Doc, null),\n\t\t\t\tK1= proplists:get_value(<<\"_id\">>, Doc, null),\n\t\t\t\tV1= proplists:get_value(<<\"Rent\">>, Doc, null),\n\t\t\t\tV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\n\t\t\t\tV3= proplists:get_value(<<\"District\">>, Doc, null),\n\t\t\t\tV4= proplists:get_value(<<\"Adress\">>, Doc, null),\n\t\t\t\tV5= proplists:get_value(<<\"Area\">>, Doc, null),\n\t\t\t\t%%V6= proplists:get_value(<<\"Contract type\">>, Doc, null),\n\t\t\t\t\n\t\t\t\t Emit([Ko,K1],[V1,V2,V3,V4,V5]);\n\t\t\t\n\t_ ->\n          ok\n      end;\n    _ ->\n      ok\n  end\nend.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_0-3000_rooms_any": {
           "map": "fun({Doc}) ->\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 0, M =< 3000 ->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend end.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_3001-6000_rooms_any": {
           "map": "fun({Doc}) ->\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 3001, M =< 6000 ->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend end.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_6001-12000_rooms_any": {
           "map": "fun({Doc}) ->\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 6001, M =< 12000 ->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend end.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       },
       "rent_plus12001_rooms_any": {
           "map": "fun({Doc}) ->\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nM=list_to_integer(binary_to_list(V1)),\nM2 = list_to_binary(integer_to_list(M)),\ncase V1 of M2 when M >= 12001 ->\nKo =proplists:get_value(<<\"_rev\">>, Doc, null),\nK1= proplists:get_value(<<\"_id\">>, Doc, null),\nV1= proplists:get_value(<<\"Rent\">>, Doc, null),\nV2= proplists:get_value(<<\"Rooms\">>, Doc, null),\nV3= proplists:get_value(<<\"District\">>, Doc, null),\nV4= proplists:get_value(<<\"Adress\">>, Doc, null),\nV5= proplists:get_value(<<\"Area\">>, Doc, null),\nEmit([Ko,K1],[V1,V2,V3,V4,V5]);\n_->ok\nend end.",
           "reduce": "fun(Keys, Values, ReReduce) -> Values end."
       }
   }
}
